export enum UserActionTypes {
	FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
	FETCH_USER_ERROR = 'FETCH_USER_ERROR',
	REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS',
	REGISTER_USER_ERROR = 'REGISTER_USER_ERROR',
	LOGOUT_USER = 'LOGOUT_USER',
}
