export enum CourseActionTypes {
	FETCH_COURSES = 'FETCH_COURSES',
	FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS',
	FETCH_COURSES_ERROR = 'FETCH_COURSES_ERROR',
	SET_COURSE = 'SET_COURSE',
	REMOVE_COURSE = 'REMOVE_COURSE',
	ADD_COURSE = 'ADD_COURSE',
	DELETE_COURSE = 'DELETE_COURSE',
}
